spring:
  application:
    name: loja-roupa

  datasource:
    url: jdbc:postgresql://localhost:5432/lojaroupa
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate # opções: none | validate | update | create | create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false # boa prática para evitar lazy loading em endpoints

  jackson:
    serialization:
      indent_output: true # formata JSON de resposta

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: 8080
